# Generated by Django 4.2.19 on 2025-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=10)),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_mobile', models.IntegerField(default=0)),
            ],
        ),
    ]
