# Generated by Django 4.2.19 on 2025-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='stu_mobile',
            field=models.BigIntegerField(),
        ),
    ]
