# Generated by Django 4.2.19 on 2025-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_registration_stu_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='stu_mobile',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
